Load both datasets into Pandas and display the first 5 rows.

Check the shape, column names, and data types for both datasets.

Convert the date and datetime columns into datetime objects (if they aren’t already).

Find the total number of rows for each dataset.

Filter all transactions where cash_type is "Cash".

Filter transactions where coffee_name is "Latte" and money is greater than 200.

Find all rows where money is missing or null.

Replace all missing money values with the average money value of that dataset.

Sort the dataset by money in descending order.

From dataset 1, select only the date, money, and coffee_name columns.

In [1]:
import pandas as pd

In [2]:
df1=pd.read_csv("../Data/index_1.csv")
df2=pd.read_csv("../Data/index_2.csv")

In [3]:
df1.head()

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [4]:
df2.head()

         date             datetime cash_type  money            coffee_name
0  2025-02-08  2025-02-08 14:26:04      cash   15.0                    Tea
1  2025-02-08  2025-02-08 14:28:26      cash   15.0                    Tea
2  2025-02-08  2025-02-08 14:33:04      card   20.0               Espresso
3  2025-02-08  2025-02-08 15:51:04      card   30.0  Chocolate with coffee
4  2025-02-08  2025-02-08 16:35:01      cash   27.0    Chocolate with milk

In [5]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   object
 1   datetime     3636 non-null   object
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: float64(1), object(5)
memory usage: 170.6+ KB

In [6]:
df1[['date', 'datetime']] = df1[['date', 'datetime']].apply(pd.to_datetime)
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3636 entries, 0 to 3635
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   date         3636 non-null   datetime64[ns]
 1   datetime     3636 non-null   datetime64[ns]
 2   cash_type    3636 non-null   object
 3   card         3547 non-null   object
 4   money        3636 non-null   float64
 5   coffee_name  3636 non-null   object
dtypes: datetime64[ns](2), float64(1), object(3)
memory usage: 170.6+ KB

In [7]:
len(df1)

3636

In [8]:
df1.head(10)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte
5,2024-03-01,2024-03-01 15:39:47.726,card,ANON-0000-0000-0005,33.8,Americano with Milk
6,2024-03-01,2024-03-01 16:19:02.756,card,ANON-0000-0000-0006,38.7,Hot Chocolate
7,2024-03-01,2024-03-01 18:39:03.580,card,ANON-0000-0000-0007,33.8,Americano with Milk
8,2024-03-01,2024-03-01 19:22:01.762,card,ANON-0000-0000-0008,38.7,Cocoa
9,2024-03-01,2024-03-01 19:23:15.887,card,ANON-0000-0000-0008,33.8,Americano with Milk

In [9]:

df1[df1['cash_type']=='cash']

,date,datetime,cash_type,card,money,coffee_name
12,2024-03-02,2024-03-02 10:30:35.668,cash,NaN,40.0,Latte
18,2024-03-03,2024-03-03 10:10:43.981,cash,NaN,40.0,Latte
41,2024-03-06,2024-03-06 12:30:27.089,cash,NaN,35.0,Americano with Milk
46,2024-03-07,2024-03-07 10:08:58.945,cash,NaN,40.0,Latte
49,2024-03-07,2024-03-07 11:25:43.977,cash,NaN,40.0,Latte
...,...,...,...,...,...,...
657,2024-05-31,2024-05-31 09:23:58.791,cash,NaN,39.0,Latte
677,2024-06-01,2024-06-01 20:54:59.267,cash,NaN,39.0,Cocoa
685,2024-06-02,2024-06-02 22:43:10.636,cash,NaN,34.0,Americano with Milk
691,2024-06-03,2024-06-03 21:42:51.734,cash,NaN,34.0,Americano with Milk
692,2024-06-03,2024-06-03 21:43:37.471,cash,NaN,34.0,Americano with Milk

In [10]:
# df1[(df1['coffee_name']=='Latte') & (df1['cash_type']=='cash') ]
df1.query("cash_type=='cash' and coffee_name=='Latte'").head()

         date                datetime cash_type card  money coffee_name
12 2024-03-02 2024-03-02 10:30:35.668      cash  NaN   40.0       Latte
18 2024-03-03 2024-03-03 10:10:43.981      cash  NaN   40.0       Latte
46 2024-03-07 2024-03-07 10:08:58.945      cash  NaN   40.0       Latte
49 2024-03-07 2024-03-07 11:25:43.977      cash  NaN   40.0       Latte
76 2024-03-10 2024-03-10 10:06:02.960      cash  NaN   40.0       Latte

In [11]:
df1.query("coffee_name=='Latte' and money>200")

Empty DataFrame
Columns: [date, datetime, cash_type, card, money, coffee_name]
Index: []

In [12]:
df1.query("money.isnull()")

Empty DataFrame
Columns: [date, datetime, cash_type, card, money, coffee_name]
Index: []

In [13]:

df1.fillna(df1['money'].mean())

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte

In [14]:
df1.sort_values('money', ascending= False)

,date,datetime,cash_type,card,money,coffee_name
46,2024-03-07,2024-03-07 10:08:58.945,cash,NaN,40.00,Latte
232,2024-04-05,2024-04-05 15:30:50.383,cash,NaN,40.00,Latte
233,2024-04-05,2024-04-05 15:54:15.768,cash,NaN,40.00,Cappuccino
235,2024-04-05,2024-04-05 16:17:43.975,cash,NaN,40.00,Cocoa
89,2024-03-12,2024-03-12 10:15:00.297,cash,NaN,40.00,Latte
...,...,...,...,...,...,...
1271,2024-08-14,2024-08-14 11:39:07.882,card,ANON-0000-0000-0095,18.12,Espresso
1193,2024-08-07,2024-08-07 13:11:16.155,card,ANON-0000-0000-0469,18.12,Espresso
1200,2024-08-08,2024-08-08 08:46:36.204,card,ANON-0000-0000-0141,18.12,Espresso
1581,2024-09-17,2024-09-17 12:38:33.768,card,ANON-0000-0000-0628,18.12,Espresso
1027,2024-07-24,2024-07-24 14:45:49.766,card,ANON-0000-0000-0012,18.12,Espresso

In [15]:
df1[['date', 'money','coffee_name']]

           date  money    coffee_name
0    2024-03-01  38.70          Latte
1    2024-03-01  38.70  Hot Chocolate
2    2024-03-01  38.70  Hot Chocolate
3    2024-03-01  28.90      Americano
4    2024-03-01  38.70          Latte
...         ...    ...            ...
3631 2025-03-23  35.76     Cappuccino
3632 2025-03-23  35.76          Cocoa
3633 2025-03-23  35.76          Cocoa
3634 2025-03-23  25.96      Americano
3635 2025-03-23  35.76          Latte

[3636 rows x 3 columns]

In [16]:
# df1.groupby('coffee_name')['money'].sum().sort_values(ascending= False)
#use agg function of better modification like adding new column name and storing values 
df1.groupby('coffee_name').agg(total_money=('money','sum')).sort_values('total_money', ascending=False).reset_index()

           coffee_name  total_money
0                Latte     27866.30
1  Americano with Milk     25269.12
2           Cappuccino     18034.14
3            Americano     15062.26
4        Hot Chocolate     10172.46
5                Cocoa      8678.16
6              Cortado      7534.86
7             Espresso      2814.28

In [17]:
df1.groupby("cash_type").agg(total_revenue=('money','sum')).reset_index()

  cash_type  total_revenue
0      card      112245.58
1      cash        3186.00

In [18]:
df1.groupby("coffee_name").agg(avrage_money_spent=("money","mean")).reset_index()

           coffee_name  avrage_money_spent
0            Americano           26.059273
1  Americano with Milk           30.666408
2           Cappuccino           35.996287
3                Cocoa           35.712593
4              Cortado           25.804315
5             Espresso           21.002090
6        Hot Chocolate           36.072553
7                Latte           35.634655

In [19]:
df1.groupby("cash_type").agg(higest_money_spent=("money","max")).reset_index()

  cash_type  higest_money_spent
0      card                38.7
1      cash                40.0

In [20]:
df1['is_high_value']= df1['money']>300
df1['is_high_value']

0       False
1       False
2       False
3       False
4       False
        ...
3631    False
3632    False
3633    False
3634    False
3635    False
Name: is_high_value, Length: 3636, dtype: bool

In [21]:
#try8ing to do innewr join


df2[['date','datetime']]=df2[['date','datetime']].apply(pd.to_datetime)
new_cofee_Dataset=pd.merge(df1,df2, on=['date','coffee_name'], how='inner', indicator=True)

In [22]:
new_cofee_Dataset

,date,datetime_x,cash_type_x,card,money_x,coffee_name,is_high_value,datetime_y,cash_type_y,money_y,_merge
0,2025-02-09,2025-02-09 12:05:05.007,card,ANON-0000-0000-1196,35.76,Latte,False,2025-02-09 16:25:15,card,33.0,both
1,2025-02-09,2025-02-09 12:05:05.007,card,ANON-0000-0000-1196,35.76,Latte,False,2025-02-09 17:47:17,card,33.0,both
2,2025-02-09,2025-02-09 12:05:05.007,card,ANON-0000-0000-1196,35.76,Latte,False,2025-02-09 18:01:22,card,33.0,both
3,2025-02-09,2025-02-09 15:14:02.345,card,ANON-0000-0000-1189,35.76,Latte,False,2025-02-09 16:25:15,card,33.0,both
4,2025-02-09,2025-02-09 15:14:02.345,card,ANON-0000-0000-1189,35.76,Latte,False,2025-02-09 17:47:17,card,33.0,both
...,...,...,...,...,...,...,...,...,...,...,...
155,2025-03-19,2025-03-19 15:12:53.164,card,ANON-0000-0000-1295,35.76,Latte,False,2025-03-19 17:44:09,cash,33.0,both
156,2025-03-19,2025-03-19 15:14:23.419,card,ANON-0000-0000-1300,35.76,Latte,False,2025-03-19 17:44:09,cash,33.0,both
157,2025-03-19,2025-03-19 16:19:33.938,card,ANON-0000-0000-1191,35.76,Latte,False,2025-03-19 17:44:09,cash,33.0,both
158,2025-03-20,2025-03-20 21:50:15.613,card,ANON-0000-0000-1298,35.76,Latte,False,2025-03-20 11:54:23,card,33.0,both
159,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino,False,2025-03-23 14:55:46,cash,30.0,both

In [23]:
new_cofee_Dataset=pd.concat([df1,df2])
new_cofee_Dataset.head()

,date,datetime,cash_type,card,money,coffee_name,is_high_value
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,False
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,False
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,False

In [24]:
new_cofee_Dataset['coffee_name'].unique()

array(['Latte', 'Hot Chocolate', 'Americano', 'Americano with Milk',
       'Cocoa', 'Cortado', 'Espresso', 'Cappuccino', 'Tea',
       'Chocolate with coffee', 'Chocolate with milk',
       'Coffee with Irish whiskey', 'Irish whiskey with milk',
       'Double Irish whiskey', 'Double espresso', 'Americano with milk',
       'Double espresso with milk', 'Caramel with Irish whiskey',
       'Super chocolate', 'Double vanilla', 'Mochaccino',
       'Caramel with chocolate', 'Irish whiskey', 'Caramel coffee',
       'Vanilla with Irish whiskey', 'Chocolate', 'Caramel with milk',
       'Coffee with chocolate', 'Irish with chocolate', 'Vanilla coffee',
       'Double ristretto', 'Hot milkshake', 'Double chocolate', 'Caramel'],
      dtype=object)

In [25]:
df2.head()

        date            datetime cash_type  money            coffee_name
0 2025-02-08 2025-02-08 14:26:04      cash   15.0                    Tea
1 2025-02-08 2025-02-08 14:28:26      cash   15.0                    Tea
2 2025-02-08 2025-02-08 14:33:04      card   20.0               Espresso
3 2025-02-08 2025-02-08 15:51:04      card   30.0  Chocolate with coffee
4 2025-02-08 2025-02-08 16:35:01      cash   27.0    Chocolate with milk

In [26]:
unique_in_df1 = df1["coffee_name"].unique()
unique_in_df2 = df2["coffee_name"].unique()
only_in_df1 = set(unique_in_df1) - set(unique_in_df2)
print(only_in_df1)

{'Cortado', 'Hot Chocolate', 'Cocoa', 'Americano with Milk'}

In [27]:
# #this method is wrong cuz if the data has all consicutive date then its fine other ways this will not work
sales_per_date=new_cofee_Dataset.groupby('date').agg(no_of_sales=('coffee_name','count')).tail(7).reset_index()
sales_per_date

        date  no_of_sales
0 2025-03-17           18
1 2025-03-18           23
2 2025-03-19           26
3 2025-03-20           23
4 2025-03-21           24
5 2025-03-22           22
6 2025-03-23           14

In [28]:
last_7_days=df1[df1['date']>=df1['date'].max()-pd.Timedelta(7)]
sales_per_day=last_7_days.groupby('date')['coffee_name'].count()
sales_per_date

        date  no_of_sales
0 2025-03-17           18
1 2025-03-18           23
2 2025-03-19           26
3 2025-03-20           23
4 2025-03-21           24
5 2025-03-22           22
6 2025-03-23           14

In [29]:
new_cofee_Dataset.head()

,date,datetime,cash_type,card,money,coffee_name,is_high_value
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,False
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,False
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,False

In [30]:
new_cofee_Dataset.groupby('date').agg(avg_money_per_transaction=('money','mean'), total_money_spent=('money','sum')).reset_index()

          date  avg_money_per_transaction  total_money_spent
0   2024-03-01                  36.027273             396.30
1   2024-03-02                  32.585714             228.10
2   2024-03-03                  34.910000             349.10
3   2024-03-04                  33.800000             135.20
4   2024-03-05                  37.611111             338.50
..         ...                        ...                ...
376 2025-03-19                  29.367692             763.56
377 2025-03-20                  29.808696             685.60
378 2025-03-21                  30.908333             741.80
379 2025-03-22                  27.882727             613.42
380 2025-03-23                  29.982857             419.76

[381 rows x 3 columns]

Advance level

Using .groupby(), find the top 2 most sold coffees for each cash_type.

In [31]:
top2=(new_cofee_Dataset.groupby(['cash_type','coffee_name']).size().reset_index(name='sales_count'))

top_2_results=(
    top2.sort_values(['cash_type','coffee_name'],ascending=[True, False]).groupby('cash_type').head(2)
)
top_2_results

   cash_type                 coffee_name  sales_count
29      card  Vanilla with Irish whiskey            2
28      card              Vanilla coffee            1
54      cash  Vanilla with Irish whiskey            1
53      cash                         Tea            6

Create a pivot table showing cash_type as rows, coffee_name as columns, and total money as values.

In [32]:
pivoted_table = new_cofee_Dataset.pivot_table(
    index='cash_type',
    columns='coffee_name',
    values='money',
    aggfunc='sum'
)
pivoted_table

coffee_name,Americano,Americano with Milk,Americano with milk,Cappuccino,Caramel,Caramel coffee,Caramel with Irish whiskey,Caramel with chocolate,Caramel with milk,Chocolate,...,Hot milkshake,Irish whiskey,Irish whiskey with milk,Irish with chocolate,Latte,Mochaccino,Super chocolate,Tea,Vanilla coffee,Vanilla with Irish whiskey
cash_type,,,,,,,,,,,,,,,,,,,,,
card,14875.26,24751.12,700.0,17769.14,NaN,56.0,224.0,112.0,50.0,25.0,...,30.0,400.0,324.0,135.0,27535.3,60.0,112.0,150.0,27.0,56.0
cash,562.00,518.00,400.0,745.00,22.0,NaN,NaN,NaN,25.0,NaN,...,NaN,125.0,81.0,NaN,1123.0,90.0,56.0,90.0,NaN,28.0

In [33]:

num_unique = new_cofee_Dataset['coffee_name'].nunique()
print(num_unique)

34

Use .apply() to create a column money_with_tax where tax = 5%.

In [34]:
new_cofee_Dataset['maoney_with_tax']= new_cofee_Dataset['money'].apply( lambda money:money+money*0.05)

In [35]:
new_cofee_Dataset.head()

,date,datetime,cash_type,card,money,coffee_name,is_high_value,maoney_with_tax
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,False,40.635
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,False,30.345
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,False,40.635

Find the day of week (Mon–Sun) for each transaction from datetime.

In [36]:
new_cofee_Dataset['day_of_week']=new_cofee_Dataset['datetime'].dt.day_name()

In [37]:
new_cofee_Dataset.head()

,date,datetime,cash_type,card,money,coffee_name,is_high_value,maoney_with_tax,day_of_week
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,False,40.635,Friday
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,False,30.345,Friday
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,False,40.635,Friday

For each day of week, find the average money spent.

In [38]:
new_cofee_Dataset.groupby('day_of_week').agg(avrage_money_spent_perday=('money','mean')).reindex(["Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"])

             avrage_money_spent_perday
day_of_week
Monday                       31.665144
Tuesday                      31.702616
Wednesday                    31.071356
Thursday                     31.528519
Friday                       31.327065
Saturday                     30.927533
Sunday                       31.381460

Identify the hour with the highest total sales (based on datetime).

In [39]:
new_cofee_Dataset['hour']=new_cofee_Dataset['datetime'].dt.hour

In [40]:
new_cofee_Dataset.head()

,date,datetime,cash_type,card,money,coffee_name,is_high_value,maoney_with_tax,day_of_week,hour
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte,False,40.635,Friday,10
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano,False,30.345,Friday,13
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte,False,40.635,Friday,13

In [41]:
new_df=new_cofee_Dataset

In [42]:
cols = ['hour'] + [col for col in new_df.columns if col != 'cash_type']
new_df=new_df[cols]

In [43]:
new_df.head()

,hour,date,datetime,card,money,coffee_name,is_high_value,maoney_with_tax,day_of_week,hour
0,10,2024-03-01,2024-03-01 10:15:50.520,ANON-0000-0000-0001,38.7,Latte,False,40.635,Friday,10
1,12,2024-03-01,2024-03-01 12:19:22.539,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12
2,12,2024-03-01,2024-03-01 12:20:18.089,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12
3,13,2024-03-01,2024-03-01 13:46:33.006,ANON-0000-0000-0003,28.9,Americano,False,30.345,Friday,13
4,13,2024-03-01,2024-03-01 13:48:14.626,ANON-0000-0000-0004,38.7,Latte,False,40.635,Friday,13

Use .rolling() to calculate a 3-day moving average of daily total sales.

In [44]:
daily_total_sales=new_df.groupby("date")['money'].sum().reset_index()
daily_total_sales.head()

        date  money
0 2024-03-01  396.3
1 2024-03-02  228.1
2 2024-03-03  349.1
3 2024-03-04  135.2
4 2024-03-05  338.5

In [45]:
daily_total_sales['3_day_avg']=daily_total_sales['money'].rolling(window=3).mean()

In [46]:
daily_total_sales.head(10)

        date  money   3_day_avg
0 2024-03-01  396.3         NaN
1 2024-03-02  228.1         NaN
2 2024-03-03  349.1  324.500000
3 2024-03-04  135.2  237.466667
4 2024-03-05  338.5  274.266667
5 2024-03-06  170.2  214.633333
6 2024-03-07  220.1  242.933333
7 2024-03-08  265.5  218.600000
8 2024-03-09  479.4  321.666667
9 2024-03-10  231.6  325.500000

Create a new column is_weekend to indicate if a sale happened on Sat/Sun.

In [47]:
new_df['date']=pd.to_datetime(new_df['date'])
new_df['is_weekend']=new_df['date'].dt.day_name().isin(['Saturday','Sunday'])

In [48]:
new_df.head()

,hour,date,datetime,card,money,coffee_name,is_high_value,maoney_with_tax,day_of_week,hour,is_weekend
0,10,2024-03-01,2024-03-01 10:15:50.520,ANON-0000-0000-0001,38.7,Latte,False,40.635,Friday,10,False
1,12,2024-03-01,2024-03-01 12:19:22.539,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12,False
2,12,2024-03-01,2024-03-01 12:20:18.089,ANON-0000-0000-0002,38.7,Hot Chocolate,False,40.635,Friday,12,False
3,13,2024-03-01,2024-03-01 13:46:33.006,ANON-0000-0000-0003,28.9,Americano,False,30.345,Friday,13,False
4,13,2024-03-01,2024-03-01 13:48:14.626,ANON-0000-0000-0004,38.7,Latte,False,40.635,Friday,13,False

Use .merge() to join dataset 1 and dataset 2 by date and compare if money values are same.

In [49]:
merged_df=pd.merge(df1,df2, on=['date'], how='inner',suffixes=('_df1', '_df2'))

In [50]:
merged_df.head()

,date,datetime_df1,cash_type_df1,card,money_df1,coffee_name_df1,is_high_value,datetime_df2,cash_type_df2,money_df2,coffee_name_df2
0,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:26:04,cash,15.0,Tea
1,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:28:26,cash,15.0,Tea
2,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:33:04,card,20.0,Espresso
3,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 15:51:04,card,30.0,Chocolate with coffee
4,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 16:35:01,cash,27.0,Chocolate with milk

In [51]:
merged_df['money_match']= merged_df['money_df1']==merged_df['money_df2']

In [52]:
merged_df.head()

,date,datetime_df1,cash_type_df1,card,money_df1,coffee_name_df1,is_high_value,datetime_df2,cash_type_df2,money_df2,coffee_name_df2,money_match
0,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:26:04,cash,15.0,Tea,False
1,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:28:26,cash,15.0,Tea,False
2,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:33:04,card,20.0,Espresso,False
3,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 15:51:04,card,30.0,Chocolate with coffee,False
4,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 16:35:01,cash,27.0,Chocolate with milk,False

Detect and remove duplicate rows from each dataset.

In [53]:
dupes=merged_df[merged_df.duplicated(keep=False)].sort_values(list(merged_df.columns))

In [54]:
dupes.head()

,date,datetime_df1,cash_type_df1,card,money_df1,coffee_name_df1,is_high_value,datetime_df2,cash_type_df2,money_df2,coffee_name_df2,money_match
1577,2025-02-26,2025-02-26 08:57:37.237,card,ANON-0000-0000-1170,25.96,Americano,False,2025-02-26 09:41:12,cash,25.0,Americano with milk,False
1578,2025-02-26,2025-02-26 08:57:37.237,card,ANON-0000-0000-1170,25.96,Americano,False,2025-02-26 09:41:12,cash,25.0,Americano with milk,False
1594,2025-02-26,2025-02-26 10:11:27.140,card,ANON-0000-0000-1248,30.86,Americano with Milk,False,2025-02-26 09:41:12,cash,25.0,Americano with milk,False
1595,2025-02-26,2025-02-26 10:11:27.140,card,ANON-0000-0000-1248,30.86,Americano with Milk,False,2025-02-26 09:41:12,cash,25.0,Americano with milk,False
1611,2025-02-26,2025-02-26 10:12:25.513,card,ANON-0000-0000-1248,30.86,Americano with Milk,False,2025-02-26 09:41:12,cash,25.0,Americano with milk,False

In [55]:
df1.duplicated().sum()

np.int64(0)

In [56]:
dupes_in_df2=df2[df2.duplicated(keep=False)].sort_values(list(df2.columns))

In [57]:
dupes_in_df2.drop_duplicates(keep= 'first')

          date            datetime cash_type  money          coffee_name
110 2025-02-26 2025-02-26 09:41:12      cash   25.0  Americano with milk
255 2025-03-23 2025-03-23 10:25:48      cash   25.0  Americano with milk

Expert level Questions

Reshape the combined dataset from “long” format to “wide” format (one row per date, columns for each coffee_name with total sales).

In [58]:
merged_df.head()

,date,datetime_df1,cash_type_df1,card,money_df1,coffee_name_df1,is_high_value,datetime_df2,cash_type_df2,money_df2,coffee_name_df2,money_match
0,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:26:04,cash,15.0,Tea,False
1,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:28:26,cash,15.0,Tea,False
2,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 14:33:04,card,20.0,Espresso,False
3,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 15:51:04,card,30.0,Chocolate with coffee,False
4,2025-02-08,2025-02-08 09:01:42.933,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-08 16:35:01,cash,27.0,Chocolate with milk,False

In [59]:
wide_df=merged_df.pivot_table(columns='coffee_name_df1',index='date',values='money_df1',aggfunc='sum',fill_value=0).reset_index().rename_axis(None,axis=1)

In [60]:
wide_df.head(10)

,date,Americano,Americano with Milk,Cappuccino,Cocoa,Cortado,Espresso,Hot Chocolate,Latte
0,2025-02-08,1246.08,246.88,0.00,0.00,207.68,0.00,0.00,0.00
1,2025-02-09,415.36,493.76,0.00,1716.48,415.36,0.00,572.16,1144.32
2,2025-02-10,545.16,370.32,107.28,429.12,0.00,0.00,107.28,429.12
3,2025-02-11,155.76,308.60,0.00,143.04,0.00,42.12,71.52,143.04
4,2025-02-12,181.72,30.86,107.28,71.52,0.00,0.00,107.28,71.52
5,2025-02-13,311.52,617.20,143.04,143.04,0.00,84.24,0.00,286.08
6,2025-02-14,934.56,555.48,965.52,321.84,0.00,379.08,643.68,321.84
7,2025-02-15,363.44,432.04,750.96,0.00,0.00,0.00,500.64,0.00
8,2025-02-16,623.04,740.64,0.00,0.00,0.00,0.00,858.24,286.08
9,2025-02-17,1453.76,1234.40,572.16,0.00,0.00,336.96,286.08,858.24

Find the cumulative sum of money spent for each coffee_name.

In [61]:
wide_df.set_index('date').cumsum().reset_index().head(10)

,date,Americano,Americano with Milk,Cappuccino,Cocoa,Cortado,Espresso,Hot Chocolate,Latte
0,2025-02-08,1246.08,246.88,0.00,0.00,207.68,0.00,0.00,0.00
1,2025-02-09,1661.44,740.64,0.00,1716.48,623.04,0.00,572.16,1144.32
2,2025-02-10,2206.60,1110.96,107.28,2145.60,623.04,0.00,679.44,1573.44
3,2025-02-11,2362.36,1419.56,107.28,2288.64,623.04,42.12,750.96,1716.48
4,2025-02-12,2544.08,1450.42,214.56,2360.16,623.04,42.12,858.24,1788.00
5,2025-02-13,2855.60,2067.62,357.60,2503.20,623.04,126.36,858.24,2074.08
6,2025-02-14,3790.16,2623.10,1323.12,2825.04,623.04,505.44,1501.92,2395.92
7,2025-02-15,4153.60,3055.14,2074.08,2825.04,623.04,505.44,2002.56,2395.92
8,2025-02-16,4776.64,3795.78,2074.08,2825.04,623.04,505.44,2860.80,2682.00
9,2025-02-17,6230.40,5030.18,2646.24,2825.04,623.04,842.40,3146.88,3540.24

Use .agg() to get for each cash_type: min money, max money, median money, total money.

In [62]:
aggrigate_data=merged_df.groupby(['cash_type_df2']).agg(min_money=('money_df2','min'),max_money=('money_df2','max'),median_money=('money_df2','median'),total_money=('money_df2','sum')).reset_index().rename(columns={'cash_type_df2':'Cash_type'})

In [63]:
aggrigate_data.head()

  Cash_type  min_money  max_money  median_money  total_money
0      card       15.0       33.0          27.0      66883.0
1      cash       15.0       33.0          25.0      29579.0

Randomly sample 10% of the data without replacement.

In [80]:
random_data=merged_df.sample(frac=0.1, replace=False,random_state=42)

In [81]:
random_data

,date,datetime_df1,cash_type_df1,card,money_df1,coffee_name_df1,is_high_value,datetime_df2,cash_type_df2,money_df2,coffee_name_df2,money_match
2023,2025-02-28,2025-02-28 16:30:06.695,card,ANON-0000-0000-1170,25.96,Americano,False,2025-02-28 14:42:05,cash,33.0,Latte,False
2587,2025-03-09,2025-03-09 09:42:03.883,card,ANON-0000-0000-1268,21.06,Espresso,False,2025-03-09 18:43:39,card,27.0,Irish whiskey with milk,False
3222,2025-03-18,2025-03-18 16:09:07.577,card,ANON-0000-0000-1203,25.96,Americano,False,2025-03-18 08:25:07,card,29.0,Coffee with Irish whiskey,False
1263,2025-02-21,2025-02-21 12:56:17.998,card,ANON-0000-0000-1198,25.96,Americano,False,2025-02-21 17:12:49,card,33.0,Latte,False
781,2025-02-17,2025-02-17 18:23:52.638,card,ANON-0000-0000-1206,25.96,Americano,False,2025-02-17 18:26:38,cash,29.0,Coffee with Irish whiskey,False
...,...,...,...,...,...,...,...,...,...,...,...,...
1991,2025-02-28,2025-02-28 14:47:52.342,card,ANON-0000-0000-1163,25.96,Americano,False,2025-02-28 22:14:42,card,28.0,Double Irish whiskey,False
2669,2025-03-10,2025-03-10 12:36:14.796,card,ANON-0000-0000-1171,25.96,Americano,False,2025-03-10 12:11:09,cash,25.0,Americano,False
2987,2025-03-14,2025-03-14 17:22:14.665,card,ANON-0000-0000-1167,25.96,Americano,False,2025-03-14 13:46:07,card,28.0,Double Irish whiskey,False
3113,2025-03-17,2025-03-17 08:18:02.658,card,ANON-0000-0000-1110,25.96,Americano,False,2025-03-17 08:01:14,card,29.0,Coffee with Irish whiskey,False
721,2025-02-17,2025-02-17 12:48:58.321,card,ANON-0000-0000-1220,35.76,Cappuccino,False,2025-02-17 16:26:51,card,28.0,Caramel with Irish whiskey,False

Create a NumPy array from the money column and calculate mean, median, std deviation.

In [ ]:
numpy_array=merged_df['money_df1'].to_numpy()

AttributeError: 'numpy.ndarray' object has no attribute 'info'

In [105]:
import numpy as np
mean=numpy_array.mean()
median=np.median(numpy_array)
deviation=numpy_array.std()
print("Mean:",mean)
print("Median:",median)
print("Deviation :",deviation)

Mean: 31.180635351615525
Median: 30.86
Deviation : 4.729553410037493

Mean: 31.180635351615525
Deviation : 4.729553410037493